AllCops:
  Exclude:
    - '.bundle/**/*'
    - 'bin/**/*'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 110

Style/SymbolArray:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
