version: "3"
services:
  app:
    build:
      context: .
      args:
        - BUNDLE_WITHOUT=production
    command: rerun --background ruby bot.rb
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
